"""
Explainability Analysis Pipeline  —  Lithium Response (Binary Classification)
=============================================================================
Inputs:
    Xdf : pd.DataFrame  — clinical feature matrix
    y   : array-like    — binary lithium response (0/1)

Model:
    StandardScaler -> GridSearchCV(LogisticRegression(fit_intercept=False,
                                                      class_weight='balanced'),
                                   {'C': 10. ** np.arange(-3, 1)},
                                   cv=cv_val, n_jobs=5, scoring='accuracy')

Outer evaluation:
    cv_test = StratifiedKFold(n_splits=5, shuffle=True, random_state=8)

Public API:
    metrics                              = plot_classification_report(X, y, cv_results['estimator'], cv_test)
    shapvals_cv, X_trn_cv, shap_stats_df = shap_analysis(cv_results['estimator'], X, y, features, cv_test)
    perm_imps_cv, perm_stats_df          = permutation_importance_analysis(cv_results['estimator'], X, y, features, cv_test)
    coefs_boot, boot_stats_df            = bootstrap_stability(model, X, y, features)
    fig, ax                              = comparison_dashboard({"SHAP": shap_stats_df, ...})


Methods Text:


## Feature importance: Clinical predictors of outcome

To identify clinical variables driving lithium-response prediction, we evaluated
feature importance within the multivariate logistic-regression model using four
complementary methods.
We organised them into two methodological families that probe distinct aspects of the model.

**Perturbation-based methods (no refitting).** Three methods explain the 
already-fitted model by perturbing the inputs and measuring the effect on its 
predictions, without retraining. They are commonly grouped under the umbrella of post-hoc,
perturbation-based explainability (Molnar, 2022; Covert et al., 2021) and 
were all computed out-of-fold across the five test folds of the outer cross-validation, 
so that explanations reflect generalisation rather than training-set fit.

(i) *SHAP values* (Lundberg & Lee, 2017), assign to each feature its Shapley-value 
contribution to the log-odds of each individual prediction, providing a locally faithful, 
additive decomposition. We report the mean absolute SHAP value across out-of-fold samples as a global importance score.

(ii) *Permutation importance* (Breiman, 2001), implemented with scikit-learn (Pedregosa et al., 2011) 
(30 repeats per fold), quantifies the drop in balanced accuracy when a single feature is randomly shuffled 
on the held-out test set, thus reflecting the model's reliance on each feature.

(iii) *Haufe forward patterns* (Haufe et al., 2014) transform the discriminative
weights of the linear classifier into a forward, generative model — the forward
pattern defined as the covariance between each input feature and the model's
decision function. This correction mitigates the multicollinearity-induced
attenuation of importance estimates that arises because correlated features are
interchangeable in the model and share credit. It also distinguishes genuinely
predictive features from suppressor variables, features that improve model
performance by capturing useful but outcome-non-specific signal (e.g., age)
without being directly predictive of the outcome themselves.


**Resampling-based stability (with refitting).** A complementary family of methods 
does not perturb inputs but rather perturbs the *training sample* itself, 
refitting the model on each resample to assess the stability of its parameters 
under sampling variability. This is the resampling-based stability framework 
(Meinshausen & Bühlmann, 2010; Sauerbrei & Schumacher, 1992), often referred 
to as *bootstrap stability* when the perturbation is generated by non-parametric bootstrap.
We drew B = 200 bootstrap resamples (with replacement, preserving sample size), 
refitted the full pipeline — including standardisation and grid-search-tuned regularisation — on each resample,
and recorded the standardised logistic-regression coefficients.
For every feature we report the bootstrap mean, standard deviation, 
95 % percentile confidence interval, and sign-consistency rate 
(the percentage of bootstrap replicates in which the coefficient retained the 
sign of its bootstrap mean). Features whose effect is both large in magnitude 
and consistent in sign across resamples can be considered robust predictors, 
whereas features whose sign flips between resamples are flagged as unstable 
regardless of their average magnitude.

The two families answer different questions: perturbation-based methods 
ask *how much does the fitted model rely on this feature?*, whereas resampling-based 
stability asks *how reproducible is this feature's contribution under sampling variability?* 
We therefore report all four scores side-by-side, normalised to a common scale, 
in a comparison dashboard. Convergence across methods is taken as evidence of a 
genuine clinical predictor; divergence is flagged and discussed.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("whitegrid")

from sklearn import linear_model as lm, preprocessing
from sklearn.base import clone
from sklearn.pipeline import make_pipeline, Pipeline
from sklearn.model_selection import StratifiedKFold, GridSearchCV, cross_validate
from sklearn.inspection import permutation_importance
from sklearn.metrics import balanced_accuracy_score, make_scorer

import shap
import warnings
warnings.filterwarnings("ignore")

from utils.sklearn_utils import (pipeline_behead, get_predictor, get_coef,
                                 oof_arrays_from_cv)


################################################################################
################################################################################
from scipy import stats as scipy_stats
from sklearn.metrics import (balanced_accuracy_score, roc_auc_score,
                             classification_report,
                             precision_score, recall_score, f1_score,
                             matthews_corrcoef)

def classification_report_cv(X: np.ndarray,
                             y: np.ndarray,
                             estimators: list,
                             cv) -> pd.DataFrame:
    """
    Evaluate a set of pre-fitted CV estimators out-of-fold and return a tidy
    metrics DataFrame.

    Each metric is reported with two strategies:

    - **Average-of-folds** (avg_folds ± std_folds): metric computed within each
      fold then averaged across folds — identical to what ``cross_val_score``
      reports.
    - **Pooled OOF** (pooled_oof): out-of-fold predictions concatenated across
      all folds, then scored once on the full vector — identical to what
      ``cross_val_predict`` followed by a metric call produces.

    Recall is broken down **per class label** (``Recall (class 0)``,
    ``Recall (class 1)``, …) so that sensitivity and specificity are reported
    separately instead of being collapsed into a single binary recall.

    Parameters
    ----------
    X          : ndarray (n_samples, n_features) — raw feature matrix
    y          : ndarray (n_samples,) — true class labels
    estimators : list of fitted pipelines, one per CV fold
    cv         : CV splitter used during fitting (must match the one used to
                 produce ``estimators``)

    Returns
    -------
    avg_folds : pd.DataFrame
        One row per metric, columns: ``metric``, ``avg_folds``, ``std_folds``,
        ``se_folds``, ``pooled_oof``, ``pval``, ``fold_values``.
        ``se_folds`` = std / √n_folds.
        ``pval``: one-sided p-value — binomial test (H0: score ≤ 0.5) for
        balanced accuracy and per-class recalls; Mann-Whitney U (H0: AUC ≤ 0.5)
        for ROC-AUC; NaN for Precision, F1, MCC.
    oof : pd.DataFrame
        Pooled OOF sklearn classification_report as a DataFrame (rows = class
        labels + averages, columns = precision / recall / f1-score / support).
    y_pred_cv  : ndarray (n_samples,) — pooled OOF hard predictions
    y_proba_cv : ndarray (n_samples,) — pooled OOF predicted probabilities
    """
    
    # Average-of-folds / "score-then-average": compute the metric within each fold,
    # then average across folds.

    print("\n━━━  Average-of-folds (AOF) Classification Report ━━━")

    y_pred_cv  = np.empty(len(y), dtype=int)
    y_proba_cv = np.empty(len(y))
    fold_ba, fold_auc, fold_prec, fold_f1, fold_mcc = [], [], [], [], []
    fold_rec_cls = []   # per-fold recall for each class: list of (n_classes,) arrays

    for (_, te), pipe in zip(cv.split(X, y), estimators):
        y_pred_cv[te]  = pipe.predict(X[te])
        y_proba_cv[te] = pipe.predict_proba(X[te])[:, 1]
        fold_ba.append(balanced_accuracy_score(y[te], y_pred_cv[te]))
        fold_auc.append(roc_auc_score(y[te], y_proba_cv[te]))
        fold_prec.append(precision_score(y[te], y_pred_cv[te], zero_division=0))
        fold_rec_cls.append(recall_score(y[te], y_pred_cv[te], average=None, zero_division=0))
        fold_f1.append(f1_score(y[te], y_pred_cv[te], zero_division=0))
        fold_mcc.append(matthews_corrcoef(y[te], y_pred_cv[te]))

    classes    = np.unique(y)
    n_folds    = len(fold_ba)
    N_test     = len(y)
    rec_pooled = recall_score(y, y_pred_cv, average=None, zero_division=0)  # (n_classes,)
    ba_pooled  = balanced_accuracy_score(y, y_pred_cv)
    auc_pooled = roc_auc_score(y, y_proba_cv)

    # p-values on pooled OOF
    pval_ba  = scipy_stats.binomtest(
        k=int(ba_pooled * N_test), n=N_test, p=0.5, alternative='greater').pvalue
    labels = np.unique(y)
    if len(labels) == 2:
        pval_auc = scipy_stats.mannwhitneyu(
            y_proba_cv[y == labels[0]], y_proba_cv[y == labels[1]], alternative='greater').pvalue
    else:
        pval_auc = np.nan  # Mann-Whitney U test is not defined for multiclass AUC
    rec_pvals = [
        scipy_stats.binomtest(
            k=int(rec_pooled[i] * np.sum(y == cls)),
            n=int(np.sum(y == cls)), p=0.5, alternative='greater').pvalue
        for i, cls in enumerate(classes)
    ]

    rows = [
        ("Balanced Accuracy", fold_ba,   ba_pooled,                                      pval_ba),
        ("ROC-AUC",           fold_auc,  auc_pooled,                                     pval_auc),
        ("Precision",         fold_prec, precision_score(y, y_pred_cv, zero_division=0), np.nan),
        *[(f"Recall (class {cls})", [r[i] for r in fold_rec_cls], rec_pooled[i], rec_pvals[i])
          for i, cls in enumerate(classes)],
        ("F1",                fold_f1,   f1_score(y, y_pred_cv, zero_division=0),        np.nan),
        ("MCC",               fold_mcc,  matthews_corrcoef(y, y_pred_cv),                np.nan),
    ]
    avg_folds = pd.DataFrame(
        [(name, np.mean(folds), np.std(folds), np.std(folds) / np.sqrt(n_folds), pooled, pval, folds)
         for name, folds, pooled, pval in rows],
        columns=["metric", "avg_folds", "std_folds", "se_folds", "pooled_oof", "pval", "fold_values"],
    )

    print("\n━━━  Model Performance  ━━━")
    print(f"  {'Metric':<24}  {'Avg-of-folds':>13}  {'±SE':>6}  {'Pooled OOF':>11}  {'p-value':>9}")
    print(f"  {'-'*24}  {'-'*13}  {'-'*6}  {'-'*11}  {'-'*9}")
    for _, row in avg_folds.iterrows():
        pval_str = f"{row.pval:>9.4f}" if not np.isnan(row.pval) else f"{'':>9}"
        print(f"  {row.metric:<24}  {row.avg_folds:>13.3f}  {row.se_folds:>6.3f}  {row.pooled_oof:>11.3f}  {pval_str}")

    print("\n━━━  Out-of-Fold (OOF) Classification Report ━━━")
    oof = pd.DataFrame(classification_report(y, y_pred_cv, output_dict=True)).T
    print(oof)

    return avg_folds, oof, y_pred_cv, y_proba_cv


################################################################################


def haufe_feature_importance(estimators: list,
                             X: np.ndarray,
                             y: np.ndarray,
                             features: list,
                             cv) -> tuple:
    """
    Compute Haufe activation patterns (forward model) out-of-fold.

    Corrects for the fact that linear classifier weights are not directly
    interpretable as feature importances when features are correlated.
    The activation pattern a = Cov(X, s) where s is the decision-function
    output — Haufe et al. (2014) NeuroImage, eq. 7.

    Parameters
    ----------
    estimators : list of fitted pipelines (one per CV fold)
    X          : raw (unscaled) feature matrix
    y          : binary response array (used only for cv.split)
    features   : ordered list of feature names
    cv         : CV splitter used during fitting

    Returns
    -------
    haufe_cv      : list of ndarray (n_features,), one per fold —
                    Haufe activation pattern estimated on each fold's test set
    haufe_stats_df : DataFrame with columns [Feature, Mean, Std] sorted by
                     |Mean| desc — Mean and Std computed across folds
    """
    print("\n━━━  Haufe Forward Model  (out-of-fold)  ━━━")
    haufe_cv = []

    for fold, ((_, te), estimator) in enumerate(zip(cv.split(X, y), estimators), 1):
        if isinstance(estimator, Pipeline):
            body, head = pipeline_behead(estimator)
            X_trn_te   = body.transform(X[te])
        else:
            X_trn_te = X[te]
            head     = estimator
        predictor = get_predictor(head)
        # Haufe 2014 eq. 7: a = Cov(X, s) ≈ X_centered^T @ s / N
        # StandardScaler ensures X_trn_te is already centred.
        s = predictor.decision_function(X_trn_te)
        haufe_cv.append(X_trn_te.T @ s / len(s))
        print(f"   fold {fold} done")

    haufe_arr      = np.vstack(haufe_cv)          # (n_folds, n_features)
    haufe_stats_df = (pd.DataFrame({
        "Feature": features,
        "Mean":    haufe_arr.mean(axis=0),
        "Std":     haufe_arr.std(axis=0),
    }).sort_values("Mean", key=lambda s: s.abs(), ascending=False)
     .reset_index(drop=True))

    print("\n  Haufe activation pattern summary:")
    print(haufe_stats_df.round(4).to_string(index=False))
    return haufe_cv, haufe_stats_df

# %% ── A. SHAP — LinearExplainer ─────────────────────────────────────────────────
def shap_analysis(estimators: list,
                  X: np.ndarray,
                  y: np.ndarray,
                  features: list,
                  cv) -> tuple:
    """
    Compute out-of-fold SHAP values with LinearExplainer across the CV loop.
    Each fold's test samples are scaled with that fold's scaler and explained
    with that fold's best LogisticRegression — no leakage.

    Parameters
    ----------
    estimators : list of fitted pipelines (one per CV fold)
    X          : raw (unscaled) feature matrix
    y          : binary response array (used only for cv.split)
    features   : ordered list of feature names
    cv         : CV splitter used during fitting

    Returns
    -------
    shapvals_cv   : list of ndarray (n_test_i, n_features), one per fold —
                    raw per-fold SHAP values for downstream analysis
    X_trn_cv      : list of ndarray (n_test_i, n_features), one per fold —
                    scaled input features (body-transformed) at test time
    shap_stats_df : DataFrame with columns [Feature, Mean, Std] sorted by
                    |Mean| desc — Mean and Std of |SHAP| computed over all OOF samples
    """
    print("\n━━━  SHAP Analysis (LinearExplainer, out-of-fold)  ━━━")
    shapvals_cv = []
    X_trn_cv    = []

    for fold, ((_, te), estimator) in enumerate(zip(cv.split(X, y), estimators), 1):
        if isinstance(estimator, Pipeline):
            body, head = pipeline_behead(estimator)
            X_trn_te   = body.transform(X[te])
        else:
            X_trn_te = X[te]
            head     = estimator
        predictor = get_predictor(head)
        X_trn_cv.append(X_trn_te)
        masker    = shap.maskers.Independent(X_trn_te, max_samples=min(200, len(te)))
        explainer = shap.LinearExplainer(predictor, masker=masker)
        shapvals_cv.append(explainer.shap_values(X_trn_te))
        print(f"   fold {fold} done")

    shap_arr      = oof_arrays_from_cv(shapvals_cv, cv, X, y)
    shap_stats_df = (pd.DataFrame({
        "Feature": features,
        "Mean":    np.abs(shap_arr).mean(axis=0),
        "Std":     np.abs(shap_arr).std(axis=0),
    }).sort_values("Mean", ascending=False)
     .reset_index(drop=True))

    return shapvals_cv, X_trn_cv, shap_stats_df


def plot_shap_analysis(shapvals_cv: list,
                       X_trn_cv: list,
                       features: list,
                       cv,
                       X: np.ndarray,
                       y: np.ndarray) -> None:
    """
    Plot SHAP beeswarm, global bar chart, and dependence plots for the top-2
    features.

    Parameters
    ----------
    shapvals_cv : list of ndarray (n_test_i, n_features), one per fold — from shap_analysis
    X_trn_cv    : list of ndarray (n_test_i, n_features), one per fold — from shap_analysis
    features    : ordered list of feature names
    cv          : CV splitter used during fitting
    X           : raw feature matrix (used for OOF reconstruction)
    y           : response array (used for OOF reconstruction)
    """
    shap_vals = oof_arrays_from_cv(shapvals_cv, cv, X, y)
    X_trn     = oof_arrays_from_cv(X_trn_cv, cv, X, y)

    shap.summary_plot(shap_vals, X_trn, feature_names=features, show=False, plot_type="dot")
    plt.title("SHAP Beeswarm  —  log-odds contribution per patient (OOF)", fontsize=12)
    plt.tight_layout()
    plt.savefig("shap_beeswarm.png", dpi=150, bbox_inches="tight")
    plt.show()
    print("✔  Saved shap_beeswarm.png")

    mean_abs = pd.Series(np.abs(shap_vals).mean(axis=0),
                         index=features).sort_values(ascending=True)
    fig, ax = plt.subplots(figsize=(8, max(4, 0.35 * len(features))))
    mean_abs.plot.barh(ax=ax, color="steelblue", edgecolor="white")
    ax.set_xlabel("Mean |SHAP value|  (log-odds units)", fontsize=11)
    ax.set_title("SHAP Global Importance — Lithium Response\n"
                 "Correlated features share credit — no double-counting", fontsize=12)
    fig.tight_layout()
    fig.savefig("shap_bar.png", dpi=150, bbox_inches="tight")
    plt.show()
    print("✔  Saved shap_bar.png")

    top2 = mean_abs.nlargest(min(2, len(features))).index.tolist()
    fig, axes = plt.subplots(1, len(top2), figsize=(6 * len(top2), 4), squeeze=False)
    for ax, feat in zip(axes[0], top2):
        idx = features.index(feat)
        ax.scatter(X_trn[:, idx], shap_vals[:, idx],
                   c=shap_vals[:, idx], cmap="coolwarm", alpha=0.6, s=20)
        ax.axhline(0, color="grey", lw=0.8, linestyle="--")
        ax.set_xlabel(f"{feat}  (standardised)")
        ax.set_ylabel("SHAP value")
        ax.set_title(f"SHAP Dependence — {feat}", fontweight="bold")
    fig.tight_layout()
    fig.savefig("shap_dependence.png", dpi=150, bbox_inches="tight")
    plt.show()
    print("✔  Saved shap_dependence.png")


# %% ── B. Permutation Importance (via cv_test) ───────────────────────────────────
def permutation_importance_analysis(estimators: list,
                                    X: np.ndarray,
                                    y: np.ndarray,
                                    features: list,
                                    cv) -> tuple:
    """
    Permutation importance evaluated out-of-fold using pre-fitted CV estimators:
    for each test fold we permute features and measure the drop in balanced
    accuracy using the pipeline already fitted on that fold's training data.

    Parameters
    ----------
    estimators : list of fitted pipelines (one per CV fold)
    X          : raw (unscaled) feature matrix
    y          : binary response array
    features   : ordered list of feature names
    cv         : CV splitter used during fitting

    Returns
    -------
    imps_cv      : list of ndarray (n_repeats, n_features), one per fold —
                   raw per-repeat importances for downstream analysis
    imps_stats_df : DataFrame with columns [Feature, Mean, Std] sorted by Mean
                    desc — Mean and Std computed across folds then repeats
    """
    print("\n━━━  Permutation Importance (per cv fold, pre-fitted estimators)  ━━━")
    scorer   = make_scorer(balanced_accuracy_score)
    imps_cv = []

    for fold, ((_, te), pipe) in enumerate(zip(cv.split(X, y), estimators), 1):
        res = permutation_importance(
            pipe, X[te], y[te],
            n_repeats=30, random_state=RANDOM_STATE,
            scoring=scorer, n_jobs=-1,
        )
        imps_cv.append(res.importances.T)
        print(f"   fold {fold} done")

    imps_stats = np.vstack([imps.mean(axis=0) for imps in imps_cv])
    imps_stats_df = (pd.DataFrame({
        "Feature":    features,
        "Mean":       imps_stats.mean(axis=0),
        "Std":          imps_stats.std(axis=0),
    }).sort_values("Mean", ascending=False).reset_index(drop=True))

    print(imps_stats_df.round(4).to_string(index=False))
    return imps_cv, imps_stats_df


# %% ── C. Bootstrap Coefficient Stability ────────────────────────────────────────
def bootstrap_stability(estimator,
                        X: np.ndarray,
                        y: np.ndarray,
                        features: list,
                        B: int = 200) -> tuple:
    """
    Bootstrap coefficient stability by cloning and refitting the estimator on
    B resampled datasets, then extracting coefficients each time.

    If estimator is a Pipeline, pipeline_behead splits it into preprocessing
    body and prediction head; get_predictor unwraps any meta-estimator wrapper
    (e.g. GridSearchCV); get_coef extracts coef_ or feature_importances_.

    Parameters
    ----------
    estimator  : single unfitted sklearn estimator or Pipeline (cloned each resample)
    X          : raw feature matrix (any preprocessing lives inside estimator)
    y          : binary response array
    features   : ordered list of feature names
    B          : number of bootstrap resamples (default 200)

    Returns
    -------
    coefs_boot   : list of B ndarrays, each (1, n_features) — raw per-resample
                   coefficients, mirroring the structure of imps_cv from
                   permutation_importance_analysis
    boot_stats_df : DataFrame with columns [Feature, Mean, Std,
                    CI_low (2.5%), CI_high (97.5%), Sign consistency (%)]
                    sorted by |Mean| desc
    """
    print(f"\n━━━  Bootstrap Coefficient Stability  (B={B})  ━━━")
    rng        = np.random.default_rng(RANDOM_STATE)
    coefs_boot = []

    for _ in range(B):
        idx    = rng.choice(len(X), size=len(X), replace=True)
        fitted = clone(estimator).fit(X[idx], y[idx])

        if isinstance(fitted, Pipeline):
            _, head = pipeline_behead(fitted)
        else:
            head = fitted

        coefs_boot.append(get_coef(get_predictor(head)).reshape(1, -1))

    boot_arr = np.vstack(coefs_boot)                          # (B, n_features)
    boot_mean = boot_arr.mean(axis=0)

    boot_stats_df = (pd.DataFrame({
        "Feature":              features,
        "Mean":                 boot_mean,
        "Std":                  boot_arr.std(axis=0),
        "CI_low (2.5%)":        np.quantile(boot_arr, 0.025, axis=0),
        "CI_high (97.5%)":      np.quantile(boot_arr, 0.975, axis=0),
        "Sign consistency (%)": (100 * (np.sign(boot_arr) == np.sign(boot_mean)).mean(axis=0)).round(1),
    }).sort_values("Mean", key=lambda s: s.abs(), ascending=False)
     .reset_index(drop=True))

    print("\n  Bootstrap stability summary:")
    print(boot_stats_df.round(4).to_string(index=False))
    return coefs_boot, boot_stats_df

from scipy import stats

# def normal_scaled_interval(sd: float, n_features: int, alpha: float = 0.05) -> tuple[float, float]:
#     """
#     Central (1 - alpha) probability interval for Y = X / n_features,
#     where X ~ N(0, sd).

#     Parameters
#     ----------
#     sd          : standard deviation of X (the parent normal)
#     n_features  : scaling factor
#     alpha       : tail probability (default 0.05 → 95% interval)

#     Returns
#     -------
#     (lower, upper) : tuple of floats
#     """
#     sd_y = sd / n_features
#     z = stats.norm.ppf(1 - alpha / 2)        # 1.96 for alpha=0.05
#     half_width = z * sd_y
#     return -half_width, +half_width


# ── D. Comparison Dashboard ────────────────────────────────────────────────────
def comparison_dashboard(stats_dict: dict,
                         add_threshold_line: True) -> tuple:
    """
    Bar chart comparing normalised feature importances across methods.

    Parameters
    ----------
    stats_dict : dict mapping method name -> DataFrame [Feature, Mean, Std, ...]
        Each DataFrame must have 'Feature' and 'Mean' columns (as returned by
        shap_analysis, permutation_importance_analysis, bootstrap_stability).
        The dictionary key is used as the legend label.
    add_threshold_line : bool, default True
        If True, draw a horizontal threshold line at
        ``μ + threshold_n_std × σ`` of the cross-method mean normalised
        importance, where μ = 1 / n_features (uniform baseline) and σ is the
        standard deviation across features of that mean. Set to None to omit.

    Returns
    -------
    fig : matplotlib Figure
    ax  : matplotlib Axes
    """
    def norm(s):
        s = s.abs()
        return s / s.sum() if s.sum() > 0 else s

    features = next(iter(stats_dict.values()))["Feature"].tolist()

    all_imp = pd.DataFrame({
        label: norm(df.set_index("Feature")["Mean"]).reindex(features)
        for label, df in stats_dict.items()
    })

    avg_importance = all_imp.mean(axis=1)
    rank_order = avg_importance.sort_values(ascending=False).index
    all_imp = all_imp.loc[rank_order]
    avg_importance = avg_importance.loc[rank_order]

    fig, ax = plt.subplots(figsize=(max(11, 0.6 * len(features)), 5))
    all_imp.plot.bar(ax=ax, width=0.72, edgecolor="white")
    ax.set_title("Feature Importance — Method Comparison", fontsize=12)
    ax.set_ylabel("Normalised importance")
    ax.set_xticklabels(all_imp.index, rotation=30, ha="right")

    if add_threshold_line is not None:
        n_features = len(features)
        sd = np.std(all_imp.values) / n_features
        mu = np.mean(all_imp.values) / n_features
        alpha = 0.05 # / len(features)  # Bonferroni correction for multiple comparisons
        z = stats.norm.ppf(1 - alpha / 2)        # 1.96 for alpha=0.05
        half_width = mu + z * sd # 95% upper bound of the null distribution of mean importance
    
        ax.axhline(half_width, color="black", lw=1.2, linestyle="--",
                   label="95% upper bound of null distribution")
        # label=f"threshold ({mu:.3f} + {z:.3f} × {sd:.3f} = {half_width:.3f})"
    ax.legend(loc="upper right")
    fig.tight_layout()
    return fig, ax



# %%
# ══════════════════════════════════════════════════════════════════════════════
#  MAIN EXECUTION
# ══════════════════════════════════════════════════════════════════════════════
from config import data, config
from sklearn.impute import SimpleImputer

# %% Input data
Xdf_raw = data[config['clinical_vars']].copy()

imputer = SimpleImputer(strategy='median')
X_imp = imputer.fit_transform(Xdf_raw)
Xdf = pd.DataFrame(X_imp, columns=config['clinical_vars'])
y = data['response']
y        = np.asarray(y)
features = list(Xdf.columns)
X        = Xdf.values

RANDOM_STATE = 8
PALETTE      = "coolwarm"
C_GRID       = 10.0 ** np.arange(-3, 1)                       # [1e-3, 1e-2, 1e-1, 1]
cv_test      = StratifiedKFold(n_splits=5, shuffle=True, random_state=8)
cv_val       = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

model = make_pipeline(
        preprocessing.StandardScaler(),
        GridSearchCV(
            lm.LogisticRegression(
                fit_intercept=False,
                class_weight="balanced",
                max_iter=5000,
                solver="saga",
            ),
            param_grid={"C": C_GRID},
            cv=cv_val,
            n_jobs=5,
            scoring="accuracy",
            refit=True,
        ),
    )

# %% Fit model with nested CV and evaluate out-of-fold performance
cv_results = cross_validate(
    model, X, y, cv=cv_test,
    scoring=["balanced_accuracy", "roc_auc"],
    return_train_score=True, return_estimator=True, n_jobs=5,
)
cv = cv_test
estimators = cv_results['estimator']


avg_folds, oof, y_pred_cv, y_proba_cv = classification_report_cv(X, y, cv_results['estimator'], cv_test)
print(oof)

from utils.plot_utils import plot_roc
plot_roc(y, y_proba_cv,
          title="ROC Curve  (pooled OOF)")

# %% Feature importance Analysis

# SHAP analysis.
shapvals_cv, X_trn_cv, shap_stats_df = shap_analysis(cv_results['estimator'], X, y, features, cv_test)

plot_shap_analysis(shapvals_cv, X_trn_cv, features, cv_test, X, y)
shap_imps_cv_df = pd.DataFrame(np.vstack([np.abs(imps).mean(axis=0) for imps in shapvals_cv]), columns=features)
shap_imps_cv_df = shap_imps_cv_df[shap_imps_cv_df.mean(axis=0).sort_values(ascending=False).index]
ax = sns.barplot(data=shap_imps_cv_df, orient="h", palette="Reds_r", capsize=.1, errorbar="se")
ax.axvline(0, color="black", lw=0.8, linestyle="--")
ax.set_title("SHAP importance averaged within cv folds")
ax.set_xlabel("Mean absolute SHAP value")
plt.tight_layout()
plt.savefig("reports/importance_SHAP.png", dpi=150, bbox_inches="tight")
plt.show()

# Permutation importance analysis.
perm_imps_cv, perm_stats_df = permutation_importance_analysis(cv_results['estimator'], X, y, features, cv_test)

perm_imps_cv_df = pd.DataFrame(np.vstack([imps.mean(axis=0) for imps in perm_imps_cv]), columns=features)
perm_imps_cv_df = perm_imps_cv_df[perm_imps_cv_df.mean(axis=0).sort_values(ascending=False).index]
ax = sns.barplot(data=perm_imps_cv_df, orient="h", palette="Reds_r", capsize=.1, errorbar="se")
ax.axvline(0, color="black", lw=0.8, linestyle="--")
ax.set_title("Permutation importance averaged within cv folds")
ax.set_xlabel("Mean drop in balanced accuracy when permuted")
plt.tight_layout()
plt.savefig("reports/importance_permutation.png", dpi=150, bbox_inches="tight")
plt.show()

# Haufe forward model
haufe_cv, haufe_stats_df = haufe_feature_importance(cv_results['estimator'], X, y, features, cv_test)

haufe_cv_df = pd.DataFrame(np.vstack(haufe_cv), columns=features)
haufe_cv_df = haufe_cv_df[haufe_cv_df.abs().mean().sort_values(ascending=False).index]
ax = sns.barplot(data=haufe_cv_df, orient="h", palette="Reds_r", capsize=.1, errorbar="se")
ax.axvline(0, color="black", lw=0.8, linestyle="--")
ax.set_title("Haufe activation pattern averaged within cv folds")
ax.set_xlabel("Haufe activation (Cov(X, s))")
plt.tight_layout()
plt.savefig("reports/importance_haufe.png", dpi=150, bbox_inches="tight")
plt.show()

# Bootstrap stability
coefs_boot, boot_stats_df = bootstrap_stability(model, X, y, features)
boot_df   = pd.DataFrame(np.vstack(coefs_boot), columns=features)
#boot_df   = boot_df[boot_df.mean().sort_values(ascending=False).index]  # largest → top
boot_df   = boot_df[boot_df.abs().mean().sort_values(ascending=False).index]  # largest → top

ax = sns.boxplot(data=boot_df, orient="h", palette="Reds_r")
ax.axvline(0, color="black", lw=0.8, linestyle="--")
ax.set_title(f"Bootstrap Coefficient Stability  (B={len(coefs_boot)} resamples)")
ax.set_xlabel("Bootstrap coefficient (standardised)")
plt.tight_layout()
plt.savefig("reports/importance_bootstrap.png", dpi=150, bbox_inches="tight")
plt.show()

# Comparison dashboard

fig, ax = comparison_dashboard({
    "SHAP":             shap_stats_df,
    "Permutation":      perm_stats_df,
    "Haufe":            haufe_stats_df,
    "Bootstrap |coef|": boot_stats_df,
}, add_threshold_line=True)
fig.savefig("reports/importance_comparison.png", dpi=150, bbox_inches="tight")
plt.show()
plt.close()

# Save results to Excel
excel_path = "reports/classification_featureimportance.xlsx"
with pd.ExcelWriter(excel_path, engine="openpyxl") as writer:
    avg_folds.drop(columns="fold_values").to_excel(writer, sheet_name="metrics_avg_folds", index=False)
    oof.to_excel(writer,          sheet_name="metrics_oof")
    shap_stats_df.to_excel(writer,  sheet_name="shap_importance",   index=False)
    perm_stats_df.to_excel(writer,  sheet_name="perm_importance",   index=False)
    haufe_stats_df.to_excel(writer, sheet_name="haufe_importance",  index=False)
    boot_stats_df.to_excel(writer,  sheet_name="boot_stability",    index=False)
print(f"✔  Saved {excel_path}")
