[project]
authors = ["EDOUARD DUCHESNAY <edouard.duchesnay@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "2025_NeuroLithe"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<4"
scikit-learn = ">=1.7.1,<2"
pandas = ">=2.3.1,<3"
statsmodels = ">=0.14.5,<0.15"
seaborn = ">=0.13.2,<0.14"
ipykernel = ">=6.29.5,<7"
openpyxl = ">=3.1.5,<4"
