# -*- coding: utf-8 -*-
"""
Created on Mon Sep  8 09:04:50 2014

@author: hl237680

This script copies images in nifti compressed format selected to build a
new template in a temporary file.
Images have been selected based on the output file generated by the script
"~/gits/scripts/2013_imagen_bmi/scripts/Tools/population_demographics.py".
They will then be extracted and used to build a new template via Matlab
SPM8 module.

OUTPUT_DIR:
    "/neurospin/tmp/hl/"

"""

import os
import shutil
from glob import glob

# Pathnames
BASE_PATH = '/neurospin/imagen/processed/'
DATA_PATH = os.path.join(BASE_PATH, 'nifti')

# Output results
OUTPUT_DIR = '/neurospin/tmp/hl/'
if not os.path.exists(OUTPUT_DIR):
    os.makedirs(OUTPUT_DIR)

# Copy images selected for building the new template in OUTPUT_DIR

# Select images

subjects_id = [5352545,
               31548817,
               14900642,
               17221560,
               1298929,
               18801650,
               10974785,
               36232609,
               737577,
               20401625,
               57728231,
               98958194,
               34241299,
               65159486,
               13818625,
               26470206,
               18931943,
               18952353,
               6006399,
               12945962,
               1885390,
               7347207,
               3712195,
               13646768,
               14743165,
               43102413,
               7779851,
               28827850,
               45668095,
               67659985,
               19912904,
               21496213,
               7127936,
               10111807,
               215284,
               297685,
               4796887,
               14141334,
               2042617,
               4254555,
               6756801,
               7824030,
               9329324,
               10951966,
               17994216,
               23079648,
               6021063,
               10813059,
               3629479,
               4622874,
               3970752,
               20451157,
               4908925,
               22858673,
               9715842,
               23896510,
               240546,
               1689886,
               1038801,
               6507225,
               2758817,
               8349556,
               2996147,
               4702312,
               1380042,
               2270310,
               4941007,
               7167925,
               1383133,
               3410870,
               2109942,
               2437251,
               1123104,
               4631192,
               469693,
               1441076,
               106871,
               2757585,
               642263,
               1338177,
               3287674,
               3328367,
               75717,
               1647364,
               4285802,
               4527509,
               112288,
               1617607,
               540905,
               829055,
               4068298,
               5019076,
               613223,
               1934375,
               1023924,
               3991592]

subjects_id = ['%012d' % subject for subject in subjects_id]

# List of neuroanatomic images' pathes to use to draw a new template
for i, subject in enumerate(subjects_id):
    path_for_subject = DATA_PATH + '/' + subject
    image_path_list = glob(path_for_subject + '/Session*/'
                                     + 'ADNI_MPRAGE/'
                                     + subject
                                     + '*.nii.gz')
    image_path = image_path_list[0]
    shutil.copy(image_path, OUTPUT_DIR)

# Then, extract the .nii.gz
# Use them through SPM8 Matlab's module to build a new template