plt.plot(fpr, tpr, lw=1, label='CV ROC')
plt.plot([0, 1], [0, 1], '--', color=(0.6, 0.6, 0.6), label='Chance level')
plt.xlim([-0.05, 1.05])
plt.ylim([-0.05, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC (AUC = %0.2f)' % roc_auc)
plt.legend(loc="lower right")
plt.show()

